### ISSUE TITLE
Load HTML page into headless test

### ISSUE THREAD

**Issue by pilafmon** [anseki/test-page-loader#1]
Can **test-page-loader** be used to load an HTML page into a headless Jasmine spec?

Example code:
http://stackoverflow.com/q/40646680

**Comment by anseki** [comment]
Hi @dpilafian, thank you for the comment.
The test-page-loader works fine in a headless browser such as PhantomJS because it only handles DOM (makes `iframe`s and loads pages), it does nothing to the browser.

**Comment by anseki** [comment]
I waited for it, and no reply came, and I close this issue.

**Comment by pilafmon** [comment]
I did get it hooked up, but the `iframe` remains empty (even though the `src` attribute gets correctly set).  This may be due to the same-origin policy restriction.

**Comment by anseki** [comment]
If you don't make the browser run correctly about security, it should throw an Uncaught DOMException error. You can find that error in the log. It is unrelated to the test-page-loader.
Try this: https://github.com/anseki/test-page-loader#examples

**Comment by anseki** [comment]
BTW,
You'd better make sure whether that `iframe` is really empty or it looks like empty because JavaScript can't run.
For example, try to load a page that doesn't contain JavaScript.

**Comment by pilafmon** [comment]
Yes, the `iframe` really is empty.

This is *not* a bug in **test-page-loader**.  However, the security issue does appear to make it impractical to use **test-page-loader** to load an HTML page into a headless Jasmine spec.

**Comment by anseki** [comment]
I have never read your code, but at least, I'm using PhantomJS v2.1.1 + Jasmine v2.5.2 + test-page-loader without any problems. The test-page-loader works with PhantomJS, and Jasmine outputs that report perfectly.
As I said before, you'd better check the log (`page.onConsoleMessage`). Because that error message should be output if it has the security problem.
Also, if your code really has a problem about the same-origin by locally accessing, the code I gave will help you.
